### PR TITLE
Reopen Stained Glass pull reqeust

### PR DESCRIPTION
**Pull request by cyates559**
I'm reopening this pull request because it got closed when I merged before.

I don't seem to have the new code working correctly, but we will figure it out eventually.

```
[17:00:47] java.lang.ClassNotFoundException: JBAstrolabe
[17:00:47]      at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[17:00:47]      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:00:47]      at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
[17:00:47]      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:00:47]      at java.lang.Class.forName0(Native Method)
[17:00:47]      at java.lang.Class.forName(Class.java:264)
[17:00:47]      at net.minecraft.src.BTHNetServerHandler.handleCustomPayload(BTHNetServerHandler.java:19)
[17:00:47]      at net.minecraft.src.Packet250CustomPayload.processPacket(Packet250CustomPayload.java:43)
[17:00:47]      at net.minecraft.src.MemoryConnection.processReadPackets(MemoryConnection.java:51)
[17:00:47]      at net.minecraft.src.NetServerHandler.networkTick(NetServerHandler.java:44)
[17:00:47]      at net.minecraft.src.NetworkListenThread.networkTick(NetworkListenThread.java:51)
[17:00:47]      at net.minecraft.src.IntegratedServerListenThread.networkTick(IntegratedServerListenThread.java:76)
[17:00:47]      at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:458)
[17:00:47]      at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:378)
[17:00:47]      at net.minecraft.src.IntegratedServer.tick(IntegratedServer.java:95)
[17:00:47]      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:320)
[17:00:47]      at net.minecraft.src.ThreadMinecraftServer.run(ThreadMinecraftServer.java:14)
[17:00:47] java.lang.ClassNotFoundException: AddonManager
[17:00:47]      at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[17:00:47]      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:00:47]      at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
[17:00:47]      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:00:47]      at java.lang.Class.forName0(Native Method)
[17:00:47]      at java.lang.Class.forName(Class.java:264)
[17:00:47]      at net.minecraft.src.BTHNetServerHandler.handleCustomPayload(BTHNetServerHandler.java:28)
[17:00:47]      at net.minecraft.src.Packet250CustomPayload.processPacket(Packet250CustomPayload.java:43)
[17:00:47]      at net.minecraft.src.MemoryConnection.processReadPackets(MemoryConnection.java:51)
[17:00:47]      at net.minecraft.src.NetServerHandler.networkTick(NetServerHandler.java:44)
[17:00:47]      at net.minecraft.src.NetworkListenThread.networkTick(NetworkListenThread.java:51)
[17:00:47]      at net.minecraft.src.IntegratedServerListenThread.networkTick(IntegratedServerListenThread.java:76)
[17:00:47]      at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:458)
[17:00:47]      at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:378)
[17:00:47]      at net.minecraft.src.IntegratedServer.tick(IntegratedServer.java:95)
[17:00:47]      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:320)
[17:00:47]      at net.minecraft.src.ThreadMinecraftServer.run(ThreadMinecraftServer.java:14)
```

### CODE REVIEW

**Comment by jorgebonafe** [comment]
I'm sorry, I realized there were a few problems with BTHNetServerHandler. I have made some fixes, I believe it should be pretty much bug free now. I've updated the offending files. Can you let me know if it works now?

By the way, I didn't touch the fixes for the new versions of btw, i.e. the pick and axe problems.

**Comment by jorgebonafe** [comment]
Ok, so let me clarify a few things I did so we're on the same page. In order to have properly transparent stained glass blocks, I needed to show a different icon on the toolbar, because the toolbar won't show transparent blocks and they looked wrong as an item. I had to separate the item from the block, so crafting a stained glass block would create an item, and placing the item would place the block. But some players will already have crafted the stained glass blocks. So I wrote some code that checked if a player placed a stained glass block on the world, and if that happened, automatically replaced it in their inventory with the corresponding item version.

I needed to do some custom network packets to acomplish that, and the issue is that I already changed those classes on my own addon.

So, the rework I did now should make any mods that have custom network packets be compatible without an update on one mod require an update on all the others.

Basically, only if a new mod that uses custom packets is in the future created, all we will need to do is edit the SharedCompatibilityAddonConfig.txt file and add the class that the new addon uses to handle packages. It took some work, but it should make our lives easier.

Our addons now share three classes, GenericBTWAddonNetServerHandler, NetworkListenThread, and CustomBTWAddonNetServerHandler, that will never have to be changed again.

----------------------

By the way, on an unrelated issue, I'm getting a "java.util.ConcurrentModificationException" error on the server, that only happens when I include "Lanterns" in the config file. I couldn't figure out what the problem is, and I don't think this is being caused by my changes, because I tested a btw server with the original deco files, and I'm having this problem also.

**Comment by cyates559** [comment]
It's totally fine.  I'm following you on the whole item vs block issue.  (There are a lot of blocks like this, that have a separate item and block)

I wanted to get your code merged before any of the other new changes, since, like you mentioned, there are some "pick and axe problems" that I need to fix.  And there is someone else who has a massive pull request pending that essentially changed every single code file.

Anyways, since I write Java 8hrs a day, I will probably not look at or touch any of this until the weekend, but this pull request is my priority. I will file an issue for the ConcurrentModificationException.

Thanks for all the work you've put in :smile:

I still haven't played BTW in a while, I'm excited to see what all these new changes are about.

**Comment by jorgebonafe** [comment]
> Anyways, since I write Java 8hrs a day, I will probably not look at or touch any of this until the weekend

Yeah, it's the same for me, which is why I made these changes on the weekend also :P
 
Anyway, lemme know if it all goes well and if I can do something to help otherwise :)
> I still haven't played BTW in a while, I'm excited to see what all these new changes are about.

Oh, you're in for a wild trip :P

**Comment by cyates559** [comment]
Just to let you know, I merged this the old fashioned way (on my desktop) because I was fixing the Lanterns bug.  

Thanks for everything!

**Comment by jorgebonafe** [comment]
Ah, cool, my pleasure :) I assumed everything worked fine then? I kinda always worry I missed or screwed something up...

**Comment by cyates559** [comment]
Yeah.  I tested everything out on client/server, obfuscated and tested them both again.

**Comment by jorgebonafe** [comment]
Allright, cool :)

**Pull request merged**
